### ISSUE TITLE
paplay not available on Mac OS

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-utils#151]
On Mac OS `paplay` is not available except if installed via `brew`, default available command is `afplay`.

```
2023-05-27 18:14:41.210 - OVOS - ovos_utils.sound:play_audio:186 - ERROR - [Errno 2] No such file or directory: 'paplay'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_utils/sound/__init__.py", line 183, in play_audio
    return subprocess.Popen(play_cmd, env=environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'paplay'
```
Changing `play_wav_cmdline` option to `"play_wav_cmdline": "afplay %1"` fixed the issue but maybe it could be nice to have a binary autodetect.

**Comment by goldyfruit** [comment]
Maybe this could leverage `ovos-plugin-audio-simple`.

**Comment by ChanceNCounter** [comment]
I don’t think it’s worth trying to target Mac without pulling deps via a package manager. Apple doesn’t really care about POSIX compliance, and they’re actively hostile toward interoperability. It’ll always be a losing battle.

**Comment by goldyfruit** [comment]
> I don’t think it’s worth trying to target Mac without pulling deps via a package manager. Apple doesn’t really care about POSIX compliance, and they’re actively hostile toward interoperability. It’ll always be a losing battle.

Then I guess, `brew install sox` should be enough.

**Comment by JarbasAl** [comment]
here we can add simple platform support, we just look for installed players and pick the best one

this is fairly platform agnostic, otherwise each platform should set an override in config

related https://github.com/OpenVoiceOS/ovos-config/pull/50/commits/ce30189f5797f10bab6d3ad4d998c6d23f08c538

**Comment by mikejgray** [comment]
> I don’t think it’s worth trying to target Mac without pulling deps via a package manager. Apple doesn’t really care about POSIX compliance, and they’re actively hostile toward interoperability. It’ll always be a losing battle.

Apple is POSIX compliant and has been since 2007:
https://www.opengroup.org/openbrand/register/brand3683.htm

However, they use BSD POSIX tools instead of GNU POSIX tools, at least according to this StackOverflow post (the font of all truth, naturally /s) https://stackoverflow.com/a/5785530/12104096

Having some degree of at least configurable support for `afplay` would be nice. Brew's packages are generally hit or miss for some of these tools.
