### ISSUE TITLE
Non-blocking error when running on MacOS natively

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-utils#175]
Haven't dug into this too deeply, and it doesn't seem to affect anything too negatively, but I get this error when running in Mac OS:

```python
2023-07-02 08:57:25.383 - OVOS - ovos_utils.file_utils:get_cache_directory:61 - ERROR - 'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/mac-hivemind-RvvZJJIu-py3.11/lib/python3.11/site-packages/ovos_utils/file_utils.py", line 57, in get_cache_directory
    path = join(MemoryTempfile(fallback=True).gettempdir(), folder)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/mac-hivemind-RvvZJJIu-py3.11/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
```

**Comment by mikejgray** [comment]
Duplicates https://github.com/OpenVoiceOS/ovos-audio/issues/14
